### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by Frigyes06** [hellpig/collatz#1]
Hello!
I'm interested in setting up a BOINC project to run your code, but I'm in need of some help. I tried your email, but it doesn't work.
Please let me know if you can help!
Best,
Frigyes

**Comment by hellpig** [comment]
Hello,

Which email isn't working?

I'd be happy to help with the non-BOINC side of things!

Best,
Brad

**Comment by Frigyes06** [comment]
Hello!

Your email listed on https://www.bradleyknockel.com/
Please send me an email at eszfrigyes06@gmail.com

Best,
Frigyes
